version: '3.1'

services:

  shoppingcart-mysql:
    container_name: shoppingcart-mysql
    image: mysql:8.0.27
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopping_cart
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - $HOME/docker/volumes/shoppingcart-mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  shoppingcart-server:
    container_name: shoppingcart-server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - shoppingcart-mysql
    ports:
      - "8090:8090"