version: '3.1'

services:

  mysql:
    container_name: ecommercestarter_mysql
    image: mysql:8.0.27
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce-starter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  server:
    container_name: ecommercestarter_server
    restart: "always"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ecommerce-starter
      SPRING_PROFILES_ACTIVE: production
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8090:8090"

volumes:
  mysql_data:
    name: ecommercestarter_mysql_data


networks:
  default:
    name: ecommercestarter_network