version: '3.1'

services:

  ecommerce-starter-mysql:
    container_name: ecommerce-starter-mysql
    image: mysql:8.0.27
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce-starter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - $HOME/docker/volumes/ecommerce-starter-mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  ecommerce-starter-server:
    container_name: ecommerce-starter-server
    environment:
      MYSQL_HOST: ecommerce-starter-mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ecommerce-starter
      SPRING_PROFILES_ACTIVE: production
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ecommerce-starter-mysql
    ports:
      - "8090:8090"
