server:
  port: 8090

spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/shopping_cart"
    username: "user"
    password: "password"
    driver-class-name: "com.mysql.jdbc.Driver"
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"


jwt:
  secret: "EXFYH2J3K5N6P7R9SATCVDWEYGZH2J4M5N6Q8R9SBUCVDXFYGZJ3K4M6P7"
